package RedPic;


/**
* RedPic/RedPicClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from redpic.idl
* Tuesday, June 4, 2019 5:53:29 PM CDT
*/

public interface RedPicClientOperations 
{
  String getEmail ();
  String getUsername ();
  void update (String img, String username);
} // interface RedPicClientOperations
