package RedPic;


/**
* RedPic/Remote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from redpic.idl
* Tuesday, June 4, 2019 5:53:29 PM CDT
*/

public interface Remote extends RemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Remote
