package RedPic;


/**
* RedPic/RedPicClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from redpic.idl
* Tuesday, June 4, 2019 7:03:03 PM CDT
*/

abstract public class RedPicClientHelper
{
  private static String  _id = "IDL:RedPic/RedPicClient:1.0";

  public static void insert (org.omg.CORBA.Any a, RedPic.RedPicClient that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RedPic.RedPicClient extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RedPic.RedPicClientHelper.id (), "RedPicClient");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RedPic.RedPicClient read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RedPicClientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RedPic.RedPicClient value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RedPic.RedPicClient narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RedPic.RedPicClient)
      return (RedPic.RedPicClient)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RedPic._RedPicClientStub stub = new RedPic._RedPicClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RedPic.RedPicClient unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RedPic.RedPicClient)
      return (RedPic.RedPicClient)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RedPic._RedPicClientStub stub = new RedPic._RedPicClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
