package RedPic;

/**
* RedPic/RemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from redpic.idl
* Tuesday, June 4, 2019 7:03:04 PM CDT
*/

public final class RemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public RedPic.Remote value = null;

  public RemoteHolder ()
  {
  }

  public RemoteHolder (RedPic.Remote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RedPic.RemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RedPic.RemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RedPic.RemoteHelper.type ();
  }

}
