package RedPic;


/**
* RedPic/RemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from redpic.idl
* Tuesday, June 4, 2019 7:03:04 PM CDT
*/

public interface RemoteOperations 
{
  void uploadImage (String img, String username);
  void addClient (RedPic.RedPicClient client);
  void removeClient (RedPic.RedPicClient client);
} // interface RemoteOperations
