package RedPic;


/**
* RedPic/RemoteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from redpic.idl
* Tuesday, June 4, 2019 7:03:04 PM CDT
*/

abstract public class RemoteHelper
{
  private static String  _id = "IDL:RedPic/Remote:1.0";

  public static void insert (org.omg.CORBA.Any a, RedPic.Remote that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RedPic.Remote extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RedPic.RemoteHelper.id (), "Remote");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RedPic.Remote read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemoteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RedPic.Remote value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RedPic.Remote narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RedPic.Remote)
      return (RedPic.Remote)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RedPic._RemoteStub stub = new RedPic._RemoteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RedPic.Remote unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RedPic.Remote)
      return (RedPic.Remote)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RedPic._RemoteStub stub = new RedPic._RemoteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
